### ISSUE TITLE
Désactivation automatique d'un fond de carte

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_mobile_maps#1]
Bonjour, 

Après plusieurs tests, nous avons créé un fichier mbtiles avec mobac, l'avons chargé sur la carte sd de nos mobiles, et avons renseigné la configuration comme suit : 
`"layers": [
      {
        "label": "Carto",
        "source": "test.mbtiles"
      }
    ]`
(j'ai essayé aussi avec /CarteSD/test.mbtiles)

Quand on rentre dans occtax et qu'on arrive à la partie pointage, la carte est désactivée. Si on va sur l'icone 'layers' et qu'on active "carto", rien ne se passe, si on retourne sur l'icone layers, "carto" est automatiquement désactivé. 

Pour le moment je ne vois pas d'où peut venir le soucis, il semble que nos mbtiles sont faits en wgs84.

**Comment by camillemonchicourt** [comment]
Je ne reproduis pas le soucis.
Testé avec notre MBTILES global et grossier : https://geonature.fr/data/maps/
Mis dans la carte interne et dans ma configuration ``settings_occtac.json`` : 
```
 "map": {
    "min_zoom_editing": 16.0,
    "max_zoom": 19.0,
    "start_zoom": 10.0,
    "base_path": "/storage/emulated/0/DCIM/maps",
    "show_compass": true,
    "layers": [
      {
        "source": "demo_scan.mbtiles",
        "label": "OpenTopoMap"
      }
    ],
```

**Comment by DonovanMaillard** [comment]
Ok merci pour le retour. Je vais tester sur mon stockage interne deja...

**Comment by DonovanMaillard** [comment]
Après mise à jour vers la dernière release, j'ai récupéré le fichier demo mbtiles. J'ai copié la même config en ajustant mon paramètre base_path : 

```
{
  "area_observation_duration": 365,
  "map": {
    "min_zoom_editing": 16.0,
    "max_zoom": 19.0,
    "start_zoom": 10.0,
    "base_path": "/Phone",
    "show_compass": true,
    "layers": [
      {
        "source": "demo_scan.mbtiles",
        "label": "OpenTopoMap"
      }
    ]
  },
  "no_such_property": "no_such_value"
}
```

Le résultat est le même que précédemment, le fond se désactive systématiquement après que je l'aie activé : 
(désolé pour la qualité du gif j'ai pas mieux pour le moment...)
(ps 2 : j'ai fait le gif avec mon ancienne conf, mais j'ai bien le meme comportement avec la couche appelée OpenTopoMap et la conf à jour :) )

![carto](https://user-images.githubusercontent.com/23358384/100357843-80d70400-2ff5-11eb-896e-b38765137e80.gif)


Les logs qui correspondent à la manip : activer la modale -> cocher la carte choisie -> fermer la modale) :
[logs.log](https://github.com/PnX-SI/gn_mobile_maps/files/5603352/logs.log)

**Comment by camillemonchicourt** [comment]
Ton chemin est bizarre.
Moi pour mon stockage local j'ai : "base_path": "/storage/emulated/0/DCIM/maps",

**Comment by DonovanMaillard** [comment]
Idem avec "/storage/emulated/0" qui est le chemin renvoyé par sync ;)
