### ISSUE TITLE
configuration fond cartographique

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/gn_mobile_maps#2]
Bonjour, 

Est-ce qu'il serait possible d'avoir un exemple de configuration pour un fond carto utilisable par tout le monde style open street map ou open topo map ?

Je n'arrive pas à produire une conf qui fonctionne.

merci

**Comment by sgrimault** [comment]
Bonjour,

C'est à dire un fond disponible en ligne comme OSM ?
Actuellement ce module ne fonctionne qu'avec des fonds embarqués localement (par exemple des fichiers MBTiles), mais il est prévu une évolution prochaine pour aussi gérer et configurer des fonds via une URL WMS.

**Comment by camillemonchicourt** [comment]
Oui voir https://github.com/PnX-SI/gn_mobile_occtax/issues/51

**Comment by Amegilla** [comment]
Merci pour vos retours, j'ai pu afficher un fond carto en mbtiles. Pour nous qui travaillons sur l'occitanie, les fonds de cartes font des gros fichiers ! D'ailleurs, l'appli est très très instable sur mon redmi note8, je ne sais pas encore si c'est lié aux fonds de cartes trop volumineux ou à autre chose mais elle est inutilisable pour l'instant. Je vais faire des tests.

**Comment by camillemonchicourt** [comment]
Oui c'est possible que ton appareil galère à lire un gros fichier.
Pour vérifier, tu devrais créer un mbtiles avec moins de niveau de zoom (donc beaucoup plus léger) pour voir si ça fonctionne mieux.

**Comment by christianbieche** [comment]
bonjour Romain,
tu peux peut être utiliser le fichier de démo que m'avait donné Camille et qui fonctionne elle. J'ai exactement le même problème que toi pour l'affichage des cartes. Le retour du terrain par les utilisateurs à l'air d'indiquer que finalement une carte très précise n'est pas forcement nécessaire 
cf mon issue sur le même sujet : 
https://github.com/PnX-SI/gn_mobile_core/issues/23

Cordialement,
christian Bièche
Informatique
Cistude Nature

**Comment by camillemonchicourt** [comment]
@Amegilla, la partie fonds offline avance, voir https://github.com/PnX-SI/gn_mobile_maps/issues/4
