### ISSUE TITLE
Layer configuration min-max zoom

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/gn_mobile_maps#6]
Le min/max zoom ne semble pas pris en compte lors du chargement de la carte
Exemple de fichier de configuration
```
 "layers": [
      {
        "label": "OSM",
        "source": "https://a.tile.openstreetmap.org"
      },
      {
        "label": "Scan IGN",
        "source": "scan_ign.mbtiles"
      },{
        "label": "OTM",
        "source": "https://a.tile.opentopomap.org/",
        "properties": {
        " attribution": "© OTM contributors"
        }
      },
      {
        "label": "Mailles",
        "source": "unities.geojson",
        "properties": {
          "min_zoom": 15.0,
          "max_zoom": 19.0
        },
        "style": {
          "stroke": true,
          "color": "#FF0000",
          "weight": 8,
          "opacity": 0.9,
          "fill": false,
          "fillColor": "#FF8000",
          "fillOpacity": 0.2
        }
```
Ci dessous la configuration annoncée:
![image](https://user-images.githubusercontent.com/3088650/111183381-21a2fc80-85b0-11eb-91c2-6cf8a5ffbba3.png)
Lorsque je fait une nouvelle observation, OSM s'affiche en premier
![image](https://user-images.githubusercontent.com/3088650/111183179-f02a3100-85af-11eb-8ad7-e08de4ee8c22.png)
Puis après un certain temps le scan ign avec les mailles s'affiche
![image](https://user-images.githubusercontent.com/3088650/111183239-fd472000-85af-11eb-8a2b-b80f6f0802ae.png)
Si par la suite je zoom/dezoom la couche des mailles s'affiche bien  au niveau de zoom spécifié dans les settings
![image](https://user-images.githubusercontent.com/3088650/111183286-0801b500-85b0-11eb-80bf-6646f3211a45.png)

**Comment by amandine-sahl** [comment]
Fonctionnel avec occtax : 1.2.2

**Comment by sgrimault** [comment]
Correction déployée sur les versions 1.2.2 et supérieur de ["Occtax"](https://github.com/PnX-SI/gn_mobile_occtax) ainsi que sur les versions 2.x.
