### ISSUE TITLE
Support des fonds de carte via le webservice IGN

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_mobile_maps#8]
Actuellement,les fonds online sont supportés à partir du standard osm via osmdroid. Les API IGN ne sont pas supportées, et OpenStreetMap ne propose pas de fonds de cartes orthophotos. 

Il est proposé d'ajouter le support des fonds de carte en ligne à partir du webservice IGN

**Comment by camillemonchicourt** [comment]
Exemples :

- Plan v2 IGN : https://wxs.ign.fr/cartes/geoportail/wmts?&REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&FORMAT=image/png&LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}
  (c) IGN Geoportail
- Ortho IGN : https://wxs.ign.fr/ortho/geoportail/wmts?&REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&FORMAT=image/jpeg&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}
  (c) IGN Geoportail
- Cadastre IGN : https://wxs.ign.fr/parcellaire/geoportail/wmts?&REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&FORMAT=image/png&LAYER=CADASTRALPARCELS.PARCELS&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}
  (c) IGN Geoportail
- OpenTopoMap : https://a.tile.opentopomap.org/{z}/{x}/{y}.png
  Map data: (c) OpenStreetMap contributors, SRTM | Map style: (c) OpenTopoMap (CC-BY-SA)
- OSM : https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
  (c) OpenStreetMap contributors

**Comment by camillemonchicourt** [comment]
Fait dans la version 2.6.0 d'Occtax-mobile.
Avec la documentation associée - https://github.com/PnX-SI/gn_mobile_maps/tree/develop/maps
