### ISSUE TITLE
Produire des mbtiles performants

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/gn_mobile_maps#9]
Bonjour,

Y a t'il des configurations idéales pour produire des mbtiles performants ? 
J'ai tenté d'en faire avec les paramètres de base de QGIS (Générer des tuiles XYZ) et un WMS d'OpenStreetMap mais j'ai des difficultés à le visualiser sur mon mobile. Je n'ai rien trouvé de particulier dans la doc. Merci pour vos retours !

**Comment by camillemonchicourt** [comment]
A priori, il vaut mieux utiliser MOBAC pour les générer mais je n'ai pas de recul sur le sujet.
@xavyeah39, @amandine-sahl, @DonovanMaillard ou @sgrimault, un retour sur le sujet ?

**Comment by sgrimault** [comment]
Bonjour,
MOBAC ou QGIS font l'affaire :) bien que MOBAC cible les terminaux mobile donc j'en déduit qu'il compresse "mieux" les tuiles ?
Après quelque soit l'outil utilisé, ça reste du MBTiles (base de données SQLite avec des données indexées pour récupérer rapidement les tuiles).
Qu'entendez vous par "MBtiles performants" ? Que les tuiles s'affichent vite ? que le MBTiles en sortie ne soit pas trop gros ?

**Comment by RNF-SI** [comment]
J'ai envie de dire un peu les deux, c'est lié. Pour l'instant j'ai produit des tuiles sur le périmètre d'une réserve naturelle, donc pas très grand, avec le maximum de niveaux de tuiles, en sortie JPG compression 75 metatile size de 4 et DPI de 96, mais ça ne s'affiche pas bien sur mon mobile (fichier de 62.7 Mo). Mais j'ai utilisé un flux OSM pour la produire, de QuickMapServices, c'est peut être pas la bonne idée.
